# Generated by Django 3.1.3 on 2021-01-21 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='employee',
        ),
    ]
