# Generated by Django 3.1.3 on 2021-01-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_remove_day_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='employee',
            field=models.ManyToManyField(to='employee.Employee'),
        ),
    ]
