# Generated by Django 3.1.3 on 2021-01-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_day_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='employee',
            field=models.ManyToManyField(blank=True, null=True, to='employee.Employee'),
        ),
    ]
