# Generated by Django 3.1.3 on 2021-01-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20210121_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='employee',
            field=models.ManyToManyField(blank=True, to='employee.Employee'),
        ),
    ]
