# Generated by Django 3.1.3 on 2021-01-22 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_auto_20210121_0628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='day',
        ),
        migrations.DeleteModel(
            name='Day',
        ),
    ]
