# Generated by Django 3.1.3 on 2021-01-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_auto_20210127_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='service',
            field=models.ManyToManyField(blank=True, null=True, to='employee.Service'),
        ),
    ]
