# Generated by Django 3.1.3 on 2021-01-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_employee_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='service',
            field=models.ManyToManyField(blank=True, to='employee.Service'),
        ),
    ]
