# Generated by Django 3.1.3 on 2021-01-28 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_auto_20210127_2303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='service',
            new_name='services',
        ),
    ]
