# Generated by Django 3.1.3 on 2021-01-29 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_auto_20210127_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='ref_code',
        ),
    ]
